const NEXT_PUBLIC_API_KEY = "AIzaSyBmrmZy48iNnh44K9PjuI3KDSRlUoFhKMw";
const NEXT_PUBLIC_AUTH_DOMAIN = "glucose-a275b.firebaseapp.com";
const NEXT_PUBLIC_PROJECT_ID = "glucose-a275b";
const NEXT_PUBLIC_STORAGE_BUCKET = "glucose-a275b.appspot.com";
const NEXT_PUBLIC_MESSAGING_SENDER_ID = "147711722053";
const NEXT_PUBLIC_APP_ID = "1:147711722053:web:bc284202693dfcf424992c";
const NEXT_PUBLIC_MEASUREMENT_ID = "G-CQYP9ECV7W";

export {
    NEXT_PUBLIC_API_KEY,
    NEXT_PUBLIC_AUTH_DOMAIN,
    NEXT_PUBLIC_PROJECT_ID,
    NEXT_PUBLIC_STORAGE_BUCKET,
    NEXT_PUBLIC_MESSAGING_SENDER_ID,
    NEXT_PUBLIC_APP_ID,
    NEXT_PUBLIC_MEASUREMENT_ID
}